name: Build and Release DMG

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Tag Message
        id: tag_message
        run: |
          MESSAGE=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
          EOF=$(dd if=/dev/urandom bs=15 count=1 2>/dev/null | base64)
          echo "body<<$EOF" >> $GITHUB_OUTPUT
          echo "$MESSAGE" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run Build and Create DMG
        run: |
          swift PackageApp.swift

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Glint.dmg
          body: ${{ steps.tag_message.outputs.body }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
